service: alexa-sbahn-skill

frameworkVersion: ">=1.4.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7
  memorySize: 128
  versionFunctions: false
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

package:
  exclude:
    - tests/**
    - .git/**
    - .env
    - example-vbb-output.json
  include:
    - src/**


functions:
  alexa-handler:
    handler: src/sbahn_ticker.lambda_handler
    events:
      - alexaSkill

plugins:
  - serverless-python-requirements

# compress dependencies :P
#custom:
#  pythonRequirements:
#    zip: true
